server:
  port: '8082'

spring:
  application.name: temperature-monitoring
  datasource:
    username: sa
    url: jdbc:h2:file:~/algasensors-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE #AUTO_SERVER=TRUE para permitir múltiplas conexões no mesmo banco
    driverClassName: org.h2.Driver
    password: '123'
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch:
          count: 4 #padrão 250 valor para teste 4
        retry:
            enabled: true
            initial-interval: 10s
            max-interval: 30s
            multiplier: 2
            max-attempts: 3

          #podemos criar mais intancia do monitoring tipo duas aplicação rodando na porta 8082 e 8083
          #assim o processamento de mensagens fica mais rapido
          #para isso precisamos mudar a porta do monitoring
          #e aumentar o prefetch count para 4 ou 5 etc dependendo do sistema e aumentando o consumo
          #eles não pega as mesmas mensagens